version: '2'

networks:
  my-network:
    driver: bridge

services:
  openldap:
    build: openldap
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USERS=user01,user02
      - LDAP_PASSWORDS=password1,password2
    networks:
      - my-network
    volumes:
      - 'openldap_data:/bitnami/openldap'
  josso:
    build: josso
    ports:
      - '8081:8081'
      - '8101:8101'
      - '5005:5005'
    environment:
        - JOSSO_CLIENT_ID=idbus-f2f7244e-bbce-44ca-8b33-f5c0bde339f7
        - JOSSO_CLIENT_SECRET=7oUHlv(HLT%vxK4L
        - JOSSO_ADMIN_USR=myadmin
        - JOSSO_ADMIN_PWD=changeme
        - JOSSO_SKIP_ADMIN_CREATE=false
        - KARAF_DEBUG=true
    networks:
      - my-network

  josso-wb:
    image: atricore/josso-wb:latest
    ports:
      - '8082:8082'
    networks:
      - my-network

      
volumes:
  openldap_data:
    driver: local